Rob Ede's interview from Mainmatter's Rust interview series #226
rustacean-station/rustacean-station.org pull request #233
Opened 2023-10-16 13:11 UTC by LukeMathWalker

2023-10-18 18:39 UTC, jonhoo requested changes
Sorry for the delay! Just a few tweaks and then we can get it out tomorrow :+1:

2023-10-18 18:39 UTC, jonhoo commented on _episodes/interviews/2023-10-18-rob-ede.md
> +file: https://audio.rustacean-station.org/file/rustacean-station/2023-10-18-rob-ede.mp3
Sorry it took me so long to get to this! I've uploaded the mp3 as 2023-10-19-. Can you update this as well as the name of the `.md` file?

2023-10-18 18:39 UTC, jonhoo commented on _episodes/interviews/2023-10-18-rob-ede.md
> +[Rob Ede](https://github.com/sponsors/robjtede), lead maintainer of `actix-web`, explains to Marco Otto-Witte how (and why) Kraken chose to migrate their microservices to Rust.
I'd like a link to both `actix-web` and Kraken here

2023-10-18 18:39 UTC, jonhoo commented on _episodes/interviews/2023-10-18-rob-ede.md
> +- [@01:26] - What is `actix-web`?
Link

2023-10-18 18:39 UTC, jonhoo commented on _episodes/interviews/2023-10-18-rob-ede.md
> +- [@06:34] - Kraken's migration from Java to Rust
Link

2023-10-18 18:59 UTC, LukeMathWalker commented
I _think_ I got them all 👍🏻

2023-10-18 19:02 UTC, jonhoo approved these changes
Thanks! Some of the links could just have been sub bullets, but I'll take it 😅

2023-10-19 16:58 UTC, jonhoo commented on _episodes/interviews/2023-10-19-rob-ede.md
> +date: 2023-10-19T19:46:00Z
```suggestion
date: 2023-10-19T16:57:00Z
```

2023-10-19 17:22 UTC, merged