2023-11-17 Gabor Szabo
rustacean-station/rustacean-station.org pull request #235
Opened 2023-11-14 07:42 UTC by allenwyma

2023-11-16 21:36 UTC, jonhoo requested changes

2023-11-16 21:36 UTC, jonhoo commented on _episodes/interviews/2023-11-17-gabor-szabo.md
> +- [@38:57] - Outlining the upcoming tasks and developments planned for RustDiggar in the coming months.
```suggestion
- [@00:00] - What is Rust Digger, and why is it useful?
- [@16:36] - Handling crates without repository links (e.g., the Fastly crate)
- [@22:27] - Handling crates without an owner.
- [@30:34] - What's next for Rust Digger, including name squatting, malware, and dependency management.
- [@38:57] - What to expect in the coming months.
```
These all felt overly long and repetitive — how about this shortened version?

2023-11-16 21:36 UTC, jonhoo commented on _episodes/interviews/2023-11-17-gabor-szabo.md
> +- [@38:57] - Outlining the upcoming tasks and developments planned for RustDiggar in the coming months.
Committed these, but then marked as unresolved so you'll see them more easily

2023-11-17 12:26 UTC, jonhoo commented on _episodes/interviews/2023-11-17-gabor-szabo.md
> +date: 2023-11-17T07:00:00Z
```suggestion
date: 2023-11-17T12:26:00Z
```

2023-11-17 12:28 UTC, merged

2023-11-17 13:31 UTC, Skgland commented
I still get a 
```
{
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}
```
response for the mp3 file, with a `Cache-Control: max-age=31536000` header.
Somehow that was cached (by cloudflare?).
I don't think 404 responses should include such a long `Cache-Control` header.