2024-04-12 Marco Ieni
rustacean-station/rustacean-station.org pull request #254
Opened 2024-04-11 07:21 UTC by allenwyma

2024-04-11 07:47 UTC, jonhoo requested changes

2024-04-11 07:47 UTC, jonhoo commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +⁃ [@37:07] - Marco’s Rust podcast [RustShip](https://www.marcoieni.com/2023/08/rustship-a-new-rust-podcast/)
This looks like an incorrect apostrophe character (should be a regular ')

2024-04-11 07:47 UTC, jonhoo commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +⁃ [@00:00] - Meet Marco Ieni, software engineer at Prisma, creator of release-plz
Link to prisma?

2024-04-11 07:47 UTC, jonhoo commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +title: "Pavex with Marco Ieni"
This doesn't look right.

2024-04-11 07:51 UTC, jonhoo approved these changes

2024-04-11 07:53 UTC, jonhoo commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +⁃ [@00:00] - Meet Marco Ieni, software engineer at [Prisma](https://www.prisma.io/), creator of release-plz
Wrong kinds of dashes again?

2024-04-12 12:19 UTC, jonhoo approved these changes

2024-04-12 12:19 UTC, jonhoo commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +date: 2024-04-12T07:06:00Z
```suggestion
date: 2024-04-12T12:19:00Z
```

2024-04-12 12:22 UTC, merged

2024-04-12 17:33 UTC, robjtede commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +title: "relase-plz with Marco Ieni"
typo "relase" -> "release"

2024-04-12 18:15 UTC, robjtede commented on _episodes/interviews/2024-04-12-marco-ieni.md
> +title: "relase-plz with Marco Ieni"
https://github.com/rustacean-station/rustacean-station.org/pull/256